# Generated by Django 4.2.4 on 2023-08-24 09:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlaceName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "description_short",
                    models.TextField(verbose_name="Короткое описание"),
                ),
                (
                    "description_long",
                    tinymce.models.HTMLField(verbose_name="Полное описание"),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lon", models.FloatField(verbose_name="Долгота")),
                (
                    "point_lon",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Долгота точки"
                    ),
                ),
                (
                    "point_lat",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Широта точки"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Название в виде url",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numb", models.IntegerField(verbose_name="Порядковый номер:")),
                (
                    "picturies",
                    models.ImageField(
                        blank=True, upload_to="img", verbose_name="Картинка"
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pics",
                        to="places.placename",
                        verbose_name="Заголовок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
                "ordering": ["numb"],
            },
        ),
    ]
