# Generated by Django 4.2.4 on 2023-08-29 17:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placename",
            name="description_long",
        ),
        migrations.RemoveField(
            model_name="placename",
            name="description_short",
        ),
        migrations.AddField(
            model_name="placename",
            name="long_description",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Полное описание"
            ),
        ),
        migrations.AddField(
            model_name="placename",
            name="short_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Короткое описание"
            ),
        ),
    ]
