# Generated by Django 4.2.4 on 2023-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_remove_placename_description_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="numb",
            field=models.IntegerField(db_index=True, verbose_name="Порядковый номер:"),
        ),
    ]
