# Generated by Django 4.2.4 on 2023-09-02 16:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_image_numb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placename",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="placename",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
    ]
