# Generated by Django 4.2.4 on 2023-09-02 16:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_placename_long_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placename",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="placename",
            name="lon",
        ),
        migrations.AlterField(
            model_name="placename",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="placename",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
    ]
