# Generated by Django 4.2.4 on 2023-09-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_remove_placename_lat_remove_placename_lon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="picturies",
            new_name="pictures",
        ),
    ]
