# Generated by Django 4.2.4 on 2023-09-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_rename_picturies_image_pictures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="numb",
            field=models.IntegerField(null=True, verbose_name="Порядковый номер:"),
        ),
    ]
