# Generated by Django 4.2.4 on 2023-09-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_image_numb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="title",
            new_name="place_name",
        ),
    ]
