# Generated by Django 4.2.5 on 2023-09-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="model",
            new_name="Image",
        ),
    ]
